# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a3ac93144463927803271d4a1f08e672314d424bb64a629055ca67f4980a9a60b034c6519b76774408fe881b09f8721d43383a821d9701c89e4677f6cfd669a

test:
  secret_key_base: 932414ab23ddb508077e2d003806687c55b89ad108d3be48218f6cc6337b44869703c5c9a6e882c93157f848cbc13d6cd6ee8f9db70a36d09c5d0d24ee181282

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
